// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCAysI2xfiR465YwsvKb6JIxMq4wMp6Y',
    appId: '1:379304124296:web:502f05e18c69d02358e43d',
    messagingSenderId: '379304124296',
    projectId: 'spendly7',
    authDomain: 'spendly7.firebaseapp.com',
    storageBucket: 'spendly7.firebasestorage.app',
    measurementId: 'G-WTJDZRNVS5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIKbSspEKZTENoUKjo_FZsscBh06udmjE',
    appId: '1:379304124296:ios:68a4ead4558abb5f58e43d',
    messagingSenderId: '379304124296',
    projectId: 'spendly7',
    storageBucket: 'spendly7.firebasestorage.app',
    iosClientId: '379304124296-f30roberld8d77btaetd7t9n8j2p57pi.apps.googleusercontent.com',
    iosBundleId: 'com.jaivarshan7.spendly',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIKbSspEKZTENoUKjo_FZsscBh06udmjE',
    appId: '1:379304124296:ios:68a4ead4558abb5f58e43d',
    messagingSenderId: '379304124296',
    projectId: 'spendly7',
    storageBucket: 'spendly7.firebasestorage.app',
    iosClientId: '379304124296-f30roberld8d77btaetd7t9n8j2p57pi.apps.googleusercontent.com',
    iosBundleId: 'com.jaivarshan7.spendly',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRAOCRGb-ZfSCK2-V9WRqLkxFm8TXB1s',
    appId: '1:379304124296:android:97b86088c082bd7e58e43d',
    messagingSenderId: '379304124296',
    projectId: 'spendly7',
    storageBucket: 'spendly7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUCAysI2xfiR465YwsvKb6JIxMq4wMp6Y',
    appId: '1:379304124296:web:cde7035352b63c4f58e43d',
    messagingSenderId: '379304124296',
    projectId: 'spendly7',
    authDomain: 'spendly7.firebaseapp.com',
    storageBucket: 'spendly7.firebasestorage.app',
    measurementId: 'G-2BRCF7HTJE',
  );

}