import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';

import 'services/auth_service.dart';
import 'services/firestore_service.dart';
import 'providers/person_provider.dart';
import 'providers/transaction_provider.dart';
import 'screens/login_screen.dart';
import 'screens/dashboard_screen.dart';
import 'firebase_options.dart'; // This file is usually generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // IMPORTANT: The user needs to run `flutterfire configure` to generate firebase_options.dart
  // For now, we will assume it might be missing and handle it or provide a placeholder.
  // Since I cannot run flutterfire configure interactively, I will try to initialize with default if possible
  // or just standard initialization and expect the user to have setup google-services.json

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Fallback if options are not generated, relies on google-services.json / GoogleService-Info.plist
    await Firebase.initializeApp();
  }

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(create: (_) => AuthService()),
        StreamProvider<User?>(
          create: (context) => context.read<AuthService>().user,
          initialData: null,
        ),
      ],
      child: MaterialApp(
        title: 'Spendly',
        theme: ThemeData(
          primarySwatch: Colors.deepPurple,
          textTheme: GoogleFonts.poppinsTextTheme(),
          useMaterial3: true,
        ),
        builder: (context, child) {
          final user = Provider.of<User?>(context);
          if (user == null) {
            return LoginScreen();
          }
          // User is logged in, provide data services to the entire app (Navigator)
          return MultiProvider(
            providers: [
              Provider<FirestoreService>(
                create: (_) => FirestoreService(uid: user.uid),
              ),
              ChangeNotifierProxyProvider<FirestoreService, PersonProvider>(
                create: (context) => PersonProvider(
                  Provider.of<FirestoreService>(context, listen: false),
                ),
                update: (context, firestoreService, previous) =>
                    PersonProvider(firestoreService),
              ),
              ChangeNotifierProxyProvider<
                FirestoreService,
                TransactionProvider
              >(
                create: (context) => TransactionProvider(
                  Provider.of<FirestoreService>(context, listen: false),
                ),
                update: (_, firestoreService, __) =>
                    TransactionProvider(firestoreService),
              ),
            ],
            child: child!,
          );
        },
        home: DashboardScreen(),
      ),
    );
  }
}
